# Generated by Django 3.2.6 on 2021-08-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveSignalProgram',
            fields=[
                ('adaptive_signal_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('alarm', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adaptive_signal_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('camera_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(blank=True, max_length=45, null=True)),
                ('ip_device', models.CharField(blank=True, max_length=45, null=True)),
                ('port_device', models.SmallIntegerField(blank=True, null=True)),
                ('mac_device', models.CharField(blank=True, max_length=45, null=True)),
                ('stream_url', models.TextField()),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
            options={
                'db_table': 'camera',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('direction_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('longitude_origin', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('latitude_origin', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude_destination', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('latitude_destination', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Intersection',
            fields=[
                ('intersection_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'intersection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LightControl',
            fields=[
                ('light_control_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip_control_device', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('mac_control_device', models.CharField(blank=True, max_length=45, null=True, unique=True)),
            ],
            options={
                'db_table': 'light_control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LightControlHistory',
            fields=[
                ('light_control_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('traffic_signal_file', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'light_control_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('green_time', models.IntegerField(blank=True, null=True)),
                ('start_time_index', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficSignalProgram',
            fields=[
                ('traffic_signal_program_id', models.AutoField(primary_key=True, serialize=False)),
                ('yellow_time', models.IntegerField(blank=True, null=True)),
                ('time_transition', models.IntegerField(blank=True, null=True)),
                ('green_time_max', models.IntegerField(blank=True, null=True)),
                ('time_available_begin', models.TimeField(blank=True, null=True)),
                ('time_available_end', models.TimeField(blank=True, null=True)),
                ('weekday', models.CharField(blank=True, max_length=255, null=True)),
                ('type_program', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'traffic_signal_program',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrafficSignalProgramLog',
            fields=[
                ('traffic_signal_program_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('intersection_id', models.IntegerField(blank=True, null=True)),
                ('traffic_signal_program_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('type_program', models.IntegerField(blank=True, null=True)),
                ('time_generate_new_program', models.DateTimeField()),
            ],
            options={
                'db_table': 'traffic_signal_program_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('sso_id', models.TextField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleCounter',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('motorbike', models.IntegerField(blank=True, null=True)),
                ('car', models.IntegerField(blank=True, null=True)),
                ('bus', models.IntegerField(blank=True, null=True)),
                ('truck', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vehicle_counter',
                'managed': False,
            },
        ),
    ]
